version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
      
  eventstore:
    image: eventstore/eventstore:24.10
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true