services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    
  eventstore:
    image: eventstore/eventstore:24.10
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    
  demoweb:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: demoweb
    working_dir: /app
    volumes:
      - ./DemoWeb:/app # Mount the DemoWeb project directory
    command: ["dotnet", "build"]
    ports:
      - "5108:5108"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    
  postgresprojection:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: postgresprojection
    working_dir: /app
    volumes:
      - ./:/app
    command: ["dotnet", "build", "./PostgresProjection"]
    environment:
      - POSTGRES_HOST=postgres
      - ESDB_HOST=eventstore
    
  redisprojection:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: redisprojection
    working_dir: /app
    volumes:
      - ./:/app
    command: ["dotnet", "build", "./RedisProjection"]
    environment:
      - REDIS_HOST=redis
      - ESDB_HOST=eventstore
    
  mongoprojection:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: mongoprojection
    working_dir: /app
    volumes:
      - ./:/app
    command: ["dotnet", "build", "./MongoProjection"]
    environment:
      - MONGO_HOST=mongo
      - ESDB_HOST=eventstore
    