services:
  kurrentdb:
    image: kurrentplatform/kurrentdb:25.0
    container_name: kurrentdb
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    profiles:
      - db
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    profiles: ["db"]
  
  orderprocessor:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: orderprocessor
    working_dir: /app
    volumes:
      - ./:/app
    command: ["dotnet", "run", "--project", "./OrderProcessor"]
    environment:
      - POSTGRES_HOST=postgres
      - KURRENTDB_HOST=kurrentdb
    profiles: ["app"]