services:
  kurrentdb:
    image: kurrentplatform/kurrentdb:25.0
    container_name: kurrentdb
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    profiles:
      - db